name: .NET Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # replace with your SDK version

      - name: Restore dependencies
        run: dotnet restore ./ProductCatalog.sln

      - name: Build
        run: dotnet build ./ProductCatalog.sln --no-restore

      - name: Test
        run: dotnet test ./ProductCatalog.sln --no-build --verbosity normal